DROP DATABASE IF EXISTS BookStore;
GO

CREATE DATABASE BookStore;
GO

USE BookStore;
GO

CREATE TABLE Book (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	AuthorId INT NOT NULL,
	PublisherId INT,
	Pages INT NOT NULL,
	GenreId INT,
	YearPublishing DATE NOT NULL,
	CostPrice MONEY NOT NULL,
	Price MONEY NOT NULL,
);

CREATE TABLE Publisher (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Genre (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE DecommissionedBook (
	BookId INT PRIMARY KEY NOT NULL
);

CREATE TABLE ContinuationBook (
	BookId INT PRIMARY KEY NOT NULL,
	PredecessorId INT NOT NULL
);

CREATE TABLE Discount (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(100) UNIQUE NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	[Percent] FLOAT NOT NULL
);

CREATE TABLE [Order] (
	BookId INT NOT NULL,
	CustomerId INT NOT NULL,
	EndDate DATETIME,
	PRIMARY KEY (BookId, CustomerId)
);

CREATE TABLE BookDiscount (
	BookId INT NOT NULL,
	DiscountId INT NOT NULL,
	PRIMARY KEY (BookId, DiscountId)
);

CREATE TABLE Author (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50),
	Patronymic VARCHAR(50)
);

CREATE TABLE Customer (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50),
	Patronymic VARCHAR(50),
	Phone VARCHAR(15) NOT NULL
);

ALTER TABLE Book ADD CONSTRAINT Book_AuthorId_Author_Id FOREIGN KEY (AuthorId) REFERENCES Author(Id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Book ADD CONSTRAINT Book_PublisherId_Publisher_id FOREIGN KEY (PublisherId) REFERENCES Publisher(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Book ADD CONSTRAINT Book_GenreId_Genre_id FOREIGN KEY (GenreId) REFERENCES Genre(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DecommissionedBook ADD CONSTRAINT DecommissionedBook_BookId_Book_id FOREIGN KEY (BookId) REFERENCES Book(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ContinuationBook ADD CONSTRAINT ContinuationBook_BookId_Book_id FOREIGN KEY (BookId) REFERENCES Book(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ContinuationBook ADD CONSTRAINT ContinuationBook_PredecessorId_Book_id FOREIGN KEY (PredecessorId) REFERENCES Book(id);
ALTER TABLE [Order] ADD CONSTRAINT Order_BookId_Book_id FOREIGN KEY (BookId) REFERENCES Book(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE [Order] ADD CONSTRAINT Order_CustomerId_Customer_Id FOREIGN KEY (CustomerId) REFERENCES Customer(Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BookDiscount ADD CONSTRAINT BookDiscount_BookId_Book_id FOREIGN KEY (BookId) REFERENCES Book(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE BookDiscount ADD CONSTRAINT BookDiscount_DiscountId_Discount_id FOREIGN KEY (DiscountId) REFERENCES Discount(id) ON DELETE CASCADE ON UPDATE CASCADE;